---
- hosts: all
  tasks:
    - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
      replace:
        path: /var/www/html/index.nginx-debian.html
        regexp: '.*'
        replace: "Updated by AWX at {{ ansible_date_time.iso8601 }}"
